export const HOME_SCREEN = 'HOME_SCREEN';
export const SETTINGS_SCREEN = 'SETTINGS_SCREEN';
export const RESULTS_SCREEN = 'RESULTS_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISER_SCREEN = 'REGISER_SCREEN';
export const SUBJECTS_SCREEN = 'SUBJECTS_SCREEN';
export const QUIZZ_SCREEN = 'QUIZZ_SCREEN';
